import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fhgrabowski
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        btn_Cadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 60, 40);

        jLabel2.setText("Cnpj:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 100, 60, 40);

        jLabel3.setText("Produto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 150, 60, 40);

        jLabel4.setText("Data Ultima Compra:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 120, 40);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 60, 320, 30);
        getContentPane().add(txtCnpj);
        txtCnpj.setBounds(110, 100, 320, 30);
        getContentPane().add(txtProduto);
        txtProduto.setBounds(110, 150, 320, 30);
        getContentPane().add(txtData);
        txtData.setBounds(180, 190, 320, 30);

        btn_Cadastro.setText("Cadastro");
        btn_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cadastro);
        btn_Cadastro.setBounds(480, 320, 120, 50);

        setSize(new java.awt.Dimension(677, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroActionPerformed
// 1- pegar os dados digitados na tela
     String n, c, p,d;
     n = txtNome.getText();
     c = txtCnpj.getText();
     p = txtProduto.getText();
     d = txtData.getText();
     //2 - conectar com o banco de dados MySQL
     try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/uninove","root","admin");
     //Enviar os dados para a tabela do banco de dados
     PreparedStatement st = conectado.prepareStatement("INSERT INTO CadastroFornecedor VALUES(?,?,?,?)");
     st.setString(1, n);
     st.setString(2, c);
     st.setString(3, p);
     st.setString(4, d);
     st.executeUpdate();
     // 4- Mostrar uma menssagem indicando que cadastrou
     JOptionPane.showMessageDialog(null,"Fornecedor cadastrado com sucesso");
     txtNome.setText("");
     txtCnpj.setText("");
     txtProduto.setText("");
     txtData.setText("");
     txtNome.requestFocus();
     }catch (ClassNotFoundException ex){
       JOptionPane.showMessageDialog(null,"Driver não colocado na library");
     
     }catch (SQLException ex){
         JOptionPane.showMessageDialog(null,"Erro na conexão do banco de dados" + ex.getMessage());
     }
    }//GEN-LAST:event_btn_CadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
