import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fhgrabowski
 */
public class CadastrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        Complemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        Telefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        Referencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadasatro de Usuário");
        getContentPane().setLayout(null);

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nome.setText("Nome:");
        getContentPane().add(Nome);
        Nome.setBounds(40, 20, 60, 40);
        getContentPane().add(txtNome);
        txtNome.setBounds(120, 30, 310, 30);

        Complemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Complemento.setText("Complemento:");
        getContentPane().add(Complemento);
        Complemento.setBounds(40, 110, 120, 40);
        getContentPane().add(txtComplemento);
        txtComplemento.setBounds(160, 110, 310, 30);

        Endereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Endereco.setText("Endereço:");
        getContentPane().add(Endereco);
        Endereco.setBounds(40, 60, 90, 40);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(120, 70, 470, 30);

        Telefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telefone.setText("Telefone:");
        getContentPane().add(Telefone);
        Telefone.setBounds(40, 190, 80, 40);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(130, 190, 310, 30);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(530, 360, 110, 40);

        Referencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Referencia.setText("Referencia:");
        getContentPane().add(Referencia);
        Referencia.setBounds(40, 150, 90, 40);
        getContentPane().add(txtReferencia);
        txtReferencia.setBounds(130, 150, 310, 30);

        setSize(new java.awt.Dimension(724, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // 1- pegar os dados digitados na tela
     String n, e, c, r, t;
     n = txtNome.getText();
     e = txtEndereco.getText();
     c = txtComplemento.getText();
     r = txtReferencia.getText();
     t = txtTelefone.getText();
     //2 - conectar com o banco de dados MySQL
     try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/uninove","root","admin");
     //Enviar os dados para a tabela do banco de dados
     PreparedStatement st = conectado.prepareStatement("INSERT INTO CadastroCliente VALUES(?,?,?,?,?)");
     st.setString(1, n);
     st.setString(2, e);
     st.setString(3, c);
     st.setString(4, r);
     st.setString(5, t);
     st.executeUpdate();
     // 4- Mostrar uma menssagem indicando que cadastrou
     JOptionPane.showMessageDialog(null,"Usuario cadastrado com sucesso");
     txtNome.setText("");
     txtEndereco.setText("");
     txtComplemento.setText("");
     txtReferencia.setText("");
     txtTelefone.setText("");
     txtNome.requestFocus();
     }catch (ClassNotFoundException ex){
       JOptionPane.showMessageDialog(null,"Driver não colocado na library");
     
     }catch (SQLException ex){
         JOptionPane.showMessageDialog(null,"Erro na conexão do banco de dados" + ex.getMessage());
     }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Complemento;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Referencia;
    private javax.swing.JLabel Telefone;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
