import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fhgrabowski
 */
public class CadastrarLanche extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarLanche
     */
    public CadastrarLanche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JLabel();
        txtLanche = new javax.swing.JTextField();
        txtNome1 = new javax.swing.JLabel();
        txtIngredientes = new javax.swing.JTextField();
        txtNome2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Lanche");
        getContentPane().setLayout(null);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNome.setText("Nome:");
        getContentPane().add(txtNome);
        txtNome.setBounds(36, 38, 60, 40);
        getContentPane().add(txtLanche);
        txtLanche.setBounds(116, 48, 310, 30);

        txtNome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNome1.setText("Ingredientes:");
        getContentPane().add(txtNome1);
        txtNome1.setBounds(36, 84, 112, 40);
        getContentPane().add(txtIngredientes);
        txtIngredientes.setBounds(154, 92, 312, 30);

        txtNome2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNome2.setText("Valor:");
        getContentPane().add(txtNome2);
        txtNome2.setBounds(36, 130, 54, 40);
        getContentPane().add(txtValor);
        txtValor.setBounds(108, 138, 312, 30);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(206, 272, 145, 75);

        setSize(new java.awt.Dimension(612, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // 1- pegar os dados digitados na tela
     String l, i, v;
     l = txtLanche.getText();
     i = txtIngredientes.getText();
     v = txtValor.getText();
     //2 - conectar com o banco de dados MySQL
     try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/uninove","root","admin");
     //Enviar os dados para a tabela do banco de dados
     PreparedStatement st = conectado.prepareStatement("INSERT INTO CadastroLanche VALUES(?,?,?)");
     st.setString(1, l);
     st.setString(2, i);
     st.setString(3, v);
     st.executeUpdate();
     // 4- Mostrar uma menssagem indicando que cadastrou
     JOptionPane.showMessageDialog(null,"Lanche cadastrado com sucesso");
     txtLanche.setText("");
     txtIngredientes.setText("");
     txtValor.setText("");
     txtLanche.requestFocus();
     }catch (ClassNotFoundException ex){
       JOptionPane.showMessageDialog(null,"Driver não colocado na library");
     
     }catch (SQLException ex){
         JOptionPane.showMessageDialog(null,"Erro na conexão do banco de dados" + ex.getMessage());
     }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarLanche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JTextField txtIngredientes;
    private javax.swing.JTextField txtLanche;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNome1;
    private javax.swing.JLabel txtNome2;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
