import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fhgrabowski
 */
public class FuncionarioCadastro extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioCadastro
     */
    public FuncionarioCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        Cpf = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        EstadoCivil = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        Nascimento = new javax.swing.JLabel();
        btn_Cadastrar = new javax.swing.JButton();
        txtNascimento = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        cmbCadastro = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        txtCadastro = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        cmbCargo = new javax.swing.JComboBox<>();
        txtCargo = new javax.swing.JLabel();
        Filhos = new javax.swing.JLabel();
        cmbFilhos = new javax.swing.JComboBox<>();
        txtQtdFilhos = new javax.swing.JTextField();
        QtdFilhos = new javax.swing.JLabel();
        btn_Atualizar = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Funcionário");
        getContentPane().setLayout(null);

        Cpf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cpf.setText("Cpf:");
        getContentPane().add(Cpf);
        Cpf.setBounds(30, 40, 60, 30);

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nome.setText("Nome:");
        getContentPane().add(Nome);
        Nome.setBounds(30, 10, 60, 30);

        Telefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Telefone.setText("Telefone:");
        getContentPane().add(Telefone);
        Telefone.setBounds(30, 100, 80, 30);

        Endereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Endereco.setText("Endereço:");
        getContentPane().add(Endereco);
        Endereco.setBounds(30, 70, 90, 30);

        EstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EstadoCivil.setText("Estado Civil:");
        getContentPane().add(EstadoCivil);
        EstadoCivil.setBounds(30, 130, 100, 30);

        Senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Senha.setText("Senha:");
        getContentPane().add(Senha);
        Senha.setBounds(30, 280, 80, 30);

        Nascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nascimento.setText("Data de Nascimento:");
        getContentPane().add(Nascimento);
        Nascimento.setBounds(30, 190, 170, 30);

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cadastrar);
        btn_Cadastrar.setBounds(470, 340, 110, 40);
        getContentPane().add(txtNascimento);
        txtNascimento.setBounds(200, 200, 310, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 20, 310, 20);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(110, 50, 310, 20);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(120, 80, 310, 20);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(120, 110, 310, 20);

        cmbCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        getContentPane().add(cmbCadastro);
        cmbCadastro.setBounds(120, 230, 150, 20);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));
        getContentPane().add(cmbEstado);
        cmbEstado.setBounds(150, 140, 150, 20);

        txtCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCadastro.setText("Cadastro:");
        getContentPane().add(txtCadastro);
        txtCadastro.setBounds(30, 220, 80, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(100, 290, 310, 20);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Recepcionista", "Motoboy", "Pizzaiolo", "Aux. de Pizzaiolo" }));
        getContentPane().add(cmbCargo);
        cmbCargo.setBounds(120, 260, 150, 20);

        txtCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCargo.setText("Cargo:");
        getContentPane().add(txtCargo);
        txtCargo.setBounds(30, 250, 80, 30);

        Filhos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Filhos.setText("Filhos:");
        getContentPane().add(Filhos);
        Filhos.setBounds(30, 160, 100, 30);

        cmbFilhos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        getContentPane().add(cmbFilhos);
        cmbFilhos.setBounds(150, 170, 150, 20);
        getContentPane().add(txtQtdFilhos);
        txtQtdFilhos.setBounds(350, 170, 60, 20);

        QtdFilhos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        QtdFilhos.setText("Qnt:");
        getContentPane().add(QtdFilhos);
        QtdFilhos.setBounds(310, 160, 40, 30);

        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Atualizar);
        btn_Atualizar.setBounds(50, 340, 110, 40);

        setSize(new java.awt.Dimension(616, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
    // 1- pegar os dados digitados na tela
     String n,cp,e,t,es,f,q,d,ca,cr,s;
     n = txtNome.getText();
     cp = txtCpf.getText();
     e = txtEndereco.getText();
     t = txtTelefone.getText();
     es = cmbEstado.getSelectedItem().toString();
     f = cmbFilhos.getSelectedItem().toString();
     q = txtQtdFilhos.getText();
     d = txtNascimento.getText();
     ca = cmbCadastro.getSelectedItem().toString();
     cr = cmbCargo.getSelectedItem().toString();
     s = txtSenha.getText();
     //2 - conectar com o banco de dados MySQL
     try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/uninove","root","admin");
     //Enviar os dados para a tabela do banco de dados
     PreparedStatement st = conectado.prepareStatement("INSERT INTO CadastroFuncionario VALUES(?,?,?,?,?,?,?,?,?,?,?)");
     st.setString(1, n);
     st.setString(2, cp);
     st.setString(3, e);
     st.setString(4, t);
     st.setString(5, es);
     st.setString(6, f);
     st.setString(7, q);
     st.setString(8, d);
     st.setString(9, ca);
     st.setString(10, cr);
     st.setString(11, s);
     st.executeUpdate();
     // 4- Mostrar uma menssagem indicando que cadastrou
     JOptionPane.showMessageDialog(null,"Usuario cadastrado com sucesso");
     txtNome.setText("");
     txtEndereco.setText("");
     txtTelefone.setText("");
     cmbEstado.setSelectedIndex(1);
     cmbFilhos.setSelectedIndex(1);
     txtQtdFilhos.setText("");
     txtNascimento.setText("");
     cmbCadastro.setSelectedIndex(1);
     cmbCargo.setSelectedIndex(1);
     txtSenha.setText("");
     txtNome.requestFocus();
     }catch (ClassNotFoundException ex){
       JOptionPane.showMessageDialog(null,"Driver não colocado na library");
     
     }catch (SQLException ex){
         JOptionPane.showMessageDialog(null,"Erro na conexão do banco de dados" + ex.getMessage());
     }
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // 1- pegar os dados digitados na tela
     String e,t,es,f,q,ca,cr,s;
     e = txtEndereco.getText();
     t = txtTelefone.getText();
     es = cmbEstado.getSelectedItem().toString();
     f = cmbFilhos.getSelectedItem().toString();
     q = txtQtdFilhos.getText();
     ca = cmbCadastro.getSelectedItem().toString();
     cr = cmbCargo.getSelectedItem().toString();
     s = txtSenha.getText();
     //2 - conectar com o banco de dados MySQL
     try{
     Class.forName("com.mysql.cj.jdbc.Driver");
     Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/uninove","root","1234");
     //Enviar os dados para a tabela do banco de dados
     PreparedStatement st = conectado.prepareStatement("Update CadastroFuncionario VALUES set Endereco=?,Telefone=?,EstadoCivil=?,Filhos=?,Qnt=?,Cadastro=?,Cargo=?,Senha=? Where Cpf=?");
     st.setString(3, e);
     st.setString(4, t);
     st.setString(5, es);
     st.setString(6, f);
     st.setString(7, q);
     st.setString(9, ca);
     st.setString(10, cr);
     st.setString(11, s);
     st.executeUpdate();
      // 4- Mostrar uma menssagem indicando que cadastrou
     JOptionPane.showMessageDialog(null,"Usuario Atualizado com sucesso");
     txtNome.setText("");
     txtEndereco.setText("");
     txtTelefone.setText("");
     cmbEstado.setSelectedIndex(1);
     cmbFilhos.setSelectedIndex(1);
     txtQtdFilhos.setText("");
     txtNascimento.setText("");
     cmbCadastro.setSelectedIndex(1);
     cmbCargo.setSelectedIndex(1);
     txtSenha.setText("");
     txtNome.requestFocus();
     }catch (ClassNotFoundException ex){
       JOptionPane.showMessageDialog(null,"Driver não colocado na library");
     
     }catch (SQLException ex){
         JOptionPane.showMessageDialog(null,"Erro na conexão do banco de dados" + ex.getMessage());
     }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cpf;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel EstadoCivil;
    private javax.swing.JLabel Filhos;
    private javax.swing.JLabel Nascimento;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel QtdFilhos;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Telefone;
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JComboBox<String> cmbCadastro;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFilhos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel txtCadastro;
    private javax.swing.JLabel txtCargo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdFilhos;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
